"""
ECDSA Authentication Module - Challenge-Response Protocol
"""

import os
import hashlib
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import ec, utils
from cryptography.hazmat.primitives import serialization

class ECDSAAuthentication:
    """ECDSA-based challenge-response authentication"""
    
    def __init__(self):
        self.curve = ec.SECP256R1()
        self.private_key = None
        self.public_key = None
        
    def generate_identity_keypair(self):
        """Generate ECDSA key pair for device identity"""
        self.private_key = ec.generate_private_key(self.curve)
        self.public_key = self.private_key.public_key()
        return self.private_key, self.public_key
    
    def sign_challenge(self, challenge):
        """
        Sign a challenge (random nonce) with private key
        Returns: signature (r, s)
        """
        if not self.private_key:
            raise ValueError("Private key not generated")
        
        signature = self.private_key.sign(
            challenge,
            ec.ECDSA(hashes.SHA256())
        )
        return signature
    
    def verify_signature(self, peer_public_key, challenge, signature):
        """
        Verify peer's signature on the challenge
        Returns: True if valid, False otherwise
        """
        try:
            peer_public_key.verify(
                signature,
                challenge,
                ec.ECDSA(hashes.SHA256())
            )
            return True
        except Exception:
            return False
    
    def get_public_key_bytes(self):
        """Export public key as bytes"""
        if not self.public_key:
            return None
        return self.public_key.public_bytes(
            encoding=serialization.Encoding.X962,
            format=serialization.PublicFormat.UncompressedPoint
        )
    
    def load_peer_public_key(self, peer_bytes):
        """Load peer public key from bytes"""
        return ec.EllipticCurvePublicKey.from_encoded_point(
            self.curve, peer_bytes
        )


def demo_challenge_response():
    """Demonstrate ECDSA challenge-response authentication"""
    
    print("="*60)
    print("ECDSA Challenge-Response Authentication Demo")
    
    # Generate device identities
    print("\nGenerating device identities...")
    device_a = ECDSAAuthentication()
    device_b = ECDSAAuthentication()
    device_a.generate_identity_keypair()
    device_b.generate_identity_keypair()
    
    # Step: Challenge-Response
    print("\n--- Challenge-Response Protocol ---")
    
    # Challenge generated by Node B for Node A
    challenge = os.urandom(32)
    print(f"Challenge (Node B → Node A): {challenge.hex()[:16]}...")
    
    # Step: Node A signs the challenge
    signature = device_a.sign_challenge(challenge)
    print(f"Signature: {signature.hex()[:32]}...")
    
    # Step: Node B verifies Node A's signature
    pub_a_bytes = device_a.get_public_key_bytes()
    pub_a = device_b.load_peer_public_key(pub_a_bytes)
    
    is_valid = device_b.verify_signature(pub_a, challenge, signature)
    print(f"Signature Verified: {is_valid}")
    
    # Reverse challenge: Node A challenges Node B
    print("\n--- Reverse Challenge (Node A → Node B) ---")
    challenge_reverse = os.urandom(32)
    print(f"Challenge: {challenge_reverse.hex()[:16]}...")
    
    signature_reverse = device_b.sign_challenge(challenge_reverse)
    pub_b_bytes = device_b.get_public_key_bytes()
    pub_b = device_a.load_peer_public_key(pub_b_bytes)
    
    is_valid_reverse = device_a.verify_signature(pub_b, challenge_reverse, signature_reverse)
    print(f"Reverse Signature Verified: {is_valid_reverse}")
    
    # Mutual authentication successful
    if is_valid and is_valid_reverse:
        print("\n✓ Mutual Authentication Successful - Both devices verified")
    else:
        print("\n✗ Authentication Failed")
    
    print("="*60)

if __name__ == "__main__":
    demo_challenge_response()